### ISSUE TITLE
How to parse hyphen/minus/dash?

### ISSUE THREAD

**Issue by mgunyho** [Canop/crokey#13]
I would like for users to be able to map the key <kbd>-</kbd> in my application. This doesn't seem possible with the current implementation of the `parse` function, because it has `raw.split('-')`, so you can't do something like `parse("ctrl-alt--")`.

The simplest solution would be to add a special case like `"hyphen" => Char('-')`, kind of like how there is a special case for `"space"`. It would also be nice to document these special cases somewhere.

I can send a PR implementing this in the near future. What should the key be called? Hyphen, minus, dash? Or should we add a case for all of them? (For reference, unicode calls it "hyphen-minus".)

**Comment by Canop** [comment]
Thanks. Now, all those strings can be parsed with the expected result:

- "-"
- "hyphen"
- "minus"
- "alt--"
- "alt-hypen"
- "ctrl-alt--"
- "ctrl-alt-hyphen"

**Comment by mgunyho** [comment]
Hi, sorry for still bothering you, but did this patch make it to the release version?

With the following Cargo.toml:
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.24"
crokey = "0.5"
```
and main.rs:
```rust
use crokey::key;

fn main() {
    println!("{:?}", key!(hyphen));
}
```
I get
```
error: unrecognized key code "hyphen"
 --> src/main.rs:6:27
  |
6 |     println!("{:?}", key!(hyphen));
  |                           ^^^^^^
```

Note how this is crokey 0.5, and I checked that it's compatible with crossterm 0.24 (`use crossterm::event::KeyEvent` and then `let k: KeyEvent = key!(space)` works fine).

**Comment by mgunyho** [comment]
Hmm, `parse("hyphen")` works. But I don't understand what's going on, we have `key!(hyphen)` in the crokey tests and it works.

**Comment by Canop** [comment]
I think I know what's going on. Probably the macro sub repo not updated.

**Comment by Canop** [comment]
Can you test with version 0.5.1 of crokey ?

**Comment by mgunyho** [comment]
Yes, that seems to have fixed it, thanks!
