### ISSUE TITLE
Support Crossterm 0.25 ?

### ISSUE THREAD

**Issue by Canop** [Canop/crokey#16]
What's an event changes a lot in Crossterm 0.25.

A [KeyEvent](https://docs.rs/crossterm/latest/crossterm/event/enum.KeyEventKind.html) wraps also much more than just the keyboard's key or key combination which has been typed, now. The struct has a state and a kind, and can't be compared.

This means that crokey has to be redesigned in order to support Crossterm 0.25 (I don't know yet if that's a desirable goal).

A possible solution could be to define a struct for the identity of a key event (KeyCombination, maybe), that is the code and modifyers, make it available with a trait on KeyEvent, and build this KeyCombination in the crokey key! macro.

**Comment by TyberiusPrime** [comment]
Looking at the commit history, it seems this library now supports crossterm 0.27, hooray :+1:

**Comment by Canop** [comment]
Oh... I forgot to close this issue... Sorry

I confirm this was a lot of work, as I have a lot of crossterm-based libraries and they were broken by the changes in crossterm's data model.
