### ISSUE TITLE
Impl Serialize for KeyCombination

### ISSUE THREAD

**Issue by Julien-cpsn** [Canop/crokey#20]
Hello!

I am using your very cool lib for my project called [ATAC](https://github.com/Julien-cpsn/ATAC). I have a very long key bindings file using toml, the problem is that I would like to generate it instead of having to create it manually.

Thanks in advance

**Comment by Julien-cpsn** [comment]
Created PR https://github.com/Canop/crokey/pull/21

**Comment by Canop** [comment]
How did I forget this ?

Thanks for the PR

**Comment by Canop** [comment]
Available in 1.0.0
